### ISSUE TITLE
SFProcessTurn causing CREATE_FAILURE and stack rollback

### ISSUE THREAD

**Issue by flick1533** [aws-samples/amazon-transcribe-post-call-analytics#131]
When using the pca-main.yaml template to create the CloudFormation stack, the PCAServer will CREATE_FAIL because of the nested PCA stack entering a CREATE_FAILED state. This happens because the Lambda function SFProcessTurn fails with the error:

SFProcessTurn: CREATE_FAILED - Resources handler returned message: "Layers consume more than the available size of 262144000 bytes"

**Comment by rstrahan** [comment]
Reproduced.. thanks for reporting @flick1533. These lambda layers are dynamically created during install so perhaps the underlying packages have exanded in size and hitting this limit. We'll investigate. Thanks again.

**Comment by rstrahan** [comment]
Confirmed issue is in ffmpeg lamba layer, caused by pulling latest ffmpeg release from https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz - which, as of Spet 10th, is v5.1.1, a larger distribution that pushes the aggregate lambda layer size over the limit.
You can resolve immediately by setting CF stack parameter: `ffmpegDownloadUrl` to previous (smaller) ffmpeg build:  *https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4-amd64-static.tar.xz*
  
I'll also make a patch release of PCA to pin the ffmpeg version to 4.4 by using it as the new default value for download.
